services:
  database:
    container_name: kbot-database
    image: postgres:12
    environment:
      POSTGRES_DB: kbot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - kbot-data:/var/lib/postgresql/data

volumes:
  kbot-data:
